name: Setup Trivy
description: |
  Setup Trivy for Docker and configuration scanning
inputs:
  working-directory:
    description: |
      The working directory to use Trivy in
    required: false
    default: .
runs:
  using: composite
  steps:
    - name: Install Trivy
      run: |
        sudo apt-get install wget apt-transport-https gnupg
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null
        echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb generic main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
        sudo apt-get update
        sudo apt-get install trivy
      shell: bash
      working-directory: ${{ inputs.working-directory }}
