---
name: Setup Python
description: |
  Setup all dependencies for running Python
inputs:
  working-directory:
    description: |
      The working directory to install dependencies in
    required: true
  extensions-package-registry-password:
    description: |
      The password for the extensions package registry
    required: true
runs:
  using: composite
  steps:
    - name: Install poetry
      run: pipx install poetry==1.8.4
      shell: bash
    - uses: actions/setup-python@v5
      with:
        python-version: "3.11"
        cache: "poetry"
        cache-dependency-path: "${{ inputs.working-directory }}/poetry.lock"
    - run: poetry install
      shell: bash
      working-directory: ${{ inputs.working-directory }}
