name: Setops Deployment
on:
  workflow_call:
    inputs:
      stages:
        required: true
        type: string
      apps:
        required: true
        type: string
      setops-organization:
        description: The setops organization, defaults to zweitag
        required: false
        default: zweitag
        type: string
      setops-host:
        description: The setops host, defaults to api.setops.co
        required: false
        default: api.setops.co
        type: string
      setops-project:
        required: true
        type: string
      predeploy-command:
        required: false
        type: string
      build-context:
        description: The build context / directory where the Dockerfile is located, defaults to '.'
        required: false
        default: .
        type: string
      build-cache-key-prefix:
        description: The cache key used by docker buildx. The complete cache key is concatenated
        required: false
        default: app
        type: string
      build-args:
        description: Docker build args
        required: false
        type: string
    secrets:
      setops-username:
        required: true
      setops-password:
        required: true
      build-secrets:
        description: Docker build secrets
        required: false

jobs:
  build:
    name: Build and push image
    runs-on: ubuntu-latest
    outputs:
      image-digest: ${{ steps.build_and_push_image.outputs.image-digest }}
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2
      - name: "Build image and push it to setops image registry"
        id: build_and_push_image
        uses: zweitag/github-actions/setops-build-and-push-image@setops-make-build-args-configurable
        with:
          stages: ${{ inputs.stages }}
          apps: ${{ inputs.apps }}
          setops-username: ${{ secrets.setops-username }}
          setops-password: ${{ secrets.setops-password }}
          setops-project: ${{ inputs.setops-project }}
          setops-host: ${{ inputs.setops-host }}
          setops-organization: ${{ inputs.setops-organization }}
          build-context: ${{ inputs.build-context }}
          build-cache-key-prefix: ${{ inputs.build-cache-key-prefix }}
          build-args: ${{ inputs.build-args }}
          build-secrets: ${{ secrets.build-secrets }}

  deploy:
    name: Setops Deployment
    strategy:
      fail-fast: false
      matrix:
        stage: ${{ fromJson(inputs.stages) }}
    concurrency: setops-deployment-${{ github.ref }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2
      - name: "Deploy apps on setops"
        id: deploy
        uses: zweitag/github-actions/setops-deployment@setops-make-build-args-configurable
        with:
          stage: ${{ matrix.stage }}
          apps: ${{ inputs.apps }}
          setops-project: ${{ inputs.setops-project }}
          setops-username: ${{ secrets.setops-username }}
          setops-password: ${{ secrets.setops-password }}
          image-digest: ${{ needs.build.outputs.image-digest }}
          predeploy-command: ${{ inputs.predeploy-command }}
          setops-organization: ${{ inputs.setops-organization }}
